notifications:
  email:
    recipients:
      - mpinheir@gmail.comm
      - paganini+travis@paganini.net
    on_success: always # default: change
    on_failure: always # default: always

language: go

go:
  - 1.x

os:
  - linux

install:
  - go get -t ./...
  - go get -u golang.org/x/text/collate
  - go get -u golang.org/x/text/language
  - pushd travis && go build -o checkparticipantes && popd

script:
  - travis/checkparticipantes PARTICIPANTES.md

