baseurl = "https://osprogramadores.com/"
title = "OsProgramadores"
theme = "hugo-universal-theme"
languageCode = "pt_BR"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "pt"
# Enable comments by entering your Disqus shortname
disqusShortname = "osprogramadores-com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-2841944-4"

# Define the number of posts per page
paginate = 10

[menu]

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Regras"
    url  = "/regras/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    name = "Desafios"
    url  = "/desafios/"
    weight = 4

[[menu.main]]
    name = "Participantes"
    url  = "/participantes/"
    weight = 5

[[menu.main]]
    name = "Links"
    url  = "/links/"
    weight = 6

[[menu.main]]
    name = "Contato"
    url = "/contato/"
    weight = 7

[[menu.main]]
    name = "Colabore"
    url = "/blog/2017/04/14/contribuindo/"
    weight = 8

[params]
    viewMorePostLink = "/blog/"
    author = "mpinheir"
    defaultKeywords = ["programacao", "programas", "coding", "desenvolvimento", "desenvolvedores", "codigo"]
    defaultDescription = "Site do grupo OsProgramadores do Telegram."

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyDC2Q3c05UPOaGH-Shg6bbnTQvRbMWOR5c"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@osprogramadores.com"

    about_us = "<p>O nosso grupo não tem fins lucrativos. O nosso objetivo é disseminar conhecimento em várias áreas da ciência da computação.</p>"
    copyright = "Copyright (c) 2015 - 2017, osprogramadores.com"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    #address = ""
    latitude = "-15.7213868"
    longitude = "-48.0786626"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Quem somos"
    subtitle = "O nosso grupo é formado por pessoas de todas as idades e níveis de experiência. Nosso objetivo é disseminar o conhecimento de programação e assuntos ligados aos computadores em geral, além de formar um grupo onde todas as opiniões e perguntas sejam bem-vindas. Não há exigências ou pré-requisitos. Sua presença será sempre bem-vinda!<div class='heading text-center'><h2>Administradores</h2></div>"

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Aprenda algo novo."
    subtitle = "Tudo que você sempre quis saber sobre Programação de Computadores e nunca teve coragem de perguntar aos seus pais."
    link_url = "https://web.telegram.org/#/im?tgaddr=tg%3A%2F%2Fresolve%3Fdomain%3Dosprogramadores"
    link_text = "Junte-se a nós no Telegram"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Artigos Recentes"
    subtitle = ""

# Links section.
[params.links]
    enable = true

# Courses.
[params.links.courses]
    enable = true

# List of courses.
[[params.links.course]]
    name = "NodeStudio"
    url = "https://www.nodestudio.com.br/home"
    description = "Cursos de HTML5, CSS3, Design reponsivo, totalmente gratuitos e de qualidade com certificado."
    languages = "HTML5, CSS3"

[[params.links.course]]
    name = "Learn-C"
    url = "http://www.learn-c.org/"
    description = "Aprenda C de forma interativa sem precisar de IDE."
    languages = "C"

[[params.links.course]]
    name = "Course-Fast"
    url = "http://course.fast.ai/index.html"
    description = "Aprenda DeepLearning em vários tópicos."
    languages = "Várias"

[[params.links.course]]
    name = "Bootstrap Total"
    url = "http://www.bootstraptotal.com.br/rwd-aula-01/"
    description = "Curso de bootstrap gratuito com certificado."
    languages = "Framework Bootstrap, HTML5, CSS3"

[[params.links.course]]
    name = "FreeCodeCamp"
    url = "https://www.freecodecamp.org/"
    description = "Curso gratuito de Front e Back-end mais completo que você vai encontrar, com atividades e projetos, ao final receba um certificado."
    languages = "HTML5, CSS3, Javascript, Jquery, Bootstrap, Node.js, Git, MongoDB, etc."

[[params.links.course]]
    name = "CEV - Cursos em Video"
    url = "https://www.cursoemvideo.com/"
    description = "Cursos de Front e Back-end, Markting Digital, Banco de Dados, cursos de excelente qualidade e totalmente gratuitos."
    languages = "HTML5, CSS3, Java, Php, MySQL."

[[params.links.course]]
    name = "SoloLearn"
    url = "https://www.sololearn.com/"
    description = "Cursos introdutórios para várias linguagens de programação."
    languages = "C++, C#, Java, Python, Swift, HTML, CSS, Javascript, PHP, Ruby e SQL."

[[params.links.course]]
    name = "School of Net"
    url = "https://www.schoolofnet.com"
    description = "Cursos gratuitos de várias áreas de programação."
    languages = "Várias."

[[params.links.course]]
    name = "Code Academy"
    url = "https://www.codecademy.com"
    description = "Cursos gratuitos de Desenvolvimento web, Programação e Data Science."
    languages = "HTML, CSS, javascript, java, SQL, Ruby e outros"

[[params.links.course]]
    name = "Um tour por Go"
    url = "https://go-tour-br.appspot.com/welcome/1"
    description = "Um tour pela linguagem de Programação Go."
    languages = "Go"


# Tools.
[params.links.tools]
    enable = true

# List of tools.
[[params.links.tool]]
    name = "Regex101"
    url = "https://regex101.com/"
    description = "Ferramenta para testas suas expressões regulares em Php, Python, Javascript e Go."

[[params.links.tool]]
    name = "StackOverFlow"
    url = "https://pt.stackoverflow.com/"
    description = "Melhor fórum do mundo para programadores; use com moderação."

[[params.links.tool]]
    name = "Regex Pal"
    url = "http://www.regexpal.com/"
    description = "Outro site para testar expressões regulares."

[[params.links.tool]]
    name = "RexTester"
    url = "http://rextester.com/l/pascal_online_compiler"
    description = "Compilador online de Java, C, C#, C++, Javascript, Lua, Php, Python, Ruby, Scala entre outros."

[[params.links.tool]]
    name = "Guj"
    url = "http://www.guj.com.br/"
    description = "Fórum brasileiro para programadores."

[[params.links.tool]]
    name = "JpegMini"
    url = "http://www.jpegmini.com/"
    description = "Compacta imagens de <strong>JPEG</strong> sem perder qualidade. Excelente para deixar seu site mais leve."

[[params.links.tool]]
    name = "TinyPng"
    url = "https://tinypng.com/"
    description = "Compacte imagens de <strong>PNG</strong> sem perder qualidade. Excelente para deixar seu site mais leve."

[[params.links.tool]]
    name = "GitHub"
    url = "https://github.com/"
    description = "Se vai ser programador, essa ferramenta é essencial para hospedar seus códigos. Muitas empresas costumam pedir seu Github para analisar seus códigos. Temos um <a href='/desafios/d01/'>desafio</a> no site com tutorial ensinando a utilizá-lo."

[[params.links.tool]]
    name = "Github educacional"
    url = "https://education.github.com/pack"
    description = "Assinatura de ferramentas, créditos em sites de armazenamento e hosting, repositórios privados grátis e muito mais no pack do github para estudantes."


# Docs.
[params.links.docs]
    enable = true

# List of docs.
[[params.links.doc]]
    name = "DevDocs"
    url = "http://devdocs.io/"
    description = "DevDocs é um site que disponibiliza a documentação de centenas de linguagens."

[[params.links.doc]]
    name = "HTML, CSS, Javascript"
    url = "https://www.w3schools.com/default.asp"
    description = "Documentação front-end e back-end com muitos tutoriais."

[[params.links.doc]]
    name = "Kotlin"
    url = "https://kotlinlang.org/"
    description = "Documentação da Linguagem Kotlin."

[[params.links.doc]]
    name = "PHP"
    url = "http://php.net/manual/pt_BR/index.php"
    description = "Tudo que precisar saber sobre PHP tem nesse site, que agrega toda documentação com tutoriais em português."

[[params.links.doc]]
    name = "PHP do jeito certo"
    url = "http://br.phptherightway.com/"
    description = "Site com as melhores práticas para programadores PHP desenvolverem software dentro dos padrões adotados pela comunidade."

[[params.links.doc]]
    name = "Python"
    url = "https://wiki.python.org.br/DocumentacaoPython"
    description = "Site com link para documentação do Python, além de vários artigos e dicas de como e por onde começar com Python."


# Ebooks.
[params.links.ebooks]
    enable = true

# List of ebooks.
[[params.links.ebook]]
    name = "Java OO"
    url = "https://www.caelum.com.br/apostila-java-orientacao-objetos/"
    description = "Apostila online de Java Orientado a Objetos. Também pode ser baixada no site gratuitamente."

[[params.links.ebook]]
    name = "C#"
    url = "https://www.caelum.com.br/apostila-csharp-orientacao-objetos/"
    description = "Apostila de C#, totalmente gratuita."

[[params.links.ebook]]
    name = "Front-End"
    url = "https://www.caelum.com.br/apostila-html-css-javascript/"
    description = "Apostila de HTML, CSS e Javascript, distribuída pela Caelum de forma gratuita."

[[params.links.ebook]]
    name = "UX e Usabilidade"
    url = "https://www.caelum.com.br/apostila-ux-usabilidade-mobile-web/"
    description = "Apostila de Usabilidade mobile e Web e User Experience."

[[params.links.ebook]]
    name = "Expressões Regulares"
    url = "http://piazinho.com.br/download/expressoes-regulares-3-tabelas.pdf"
    description = "Uma tabela com um super resumo de expressões regulares, disponibilizado gratuitamente pelo autor em seu site."

[[params.links.ebook]]
    name = "Java para Web"
    url = "https://www.caelum.com.br/apostila-java-web/"
    description = "Apostila de Java para Web."


# Podcasts.
[params.links.podcasts]
    enable = true

# List of podcasts.
[[params.links.podcast]]
    name = "Jovem Nerd"
    url = "https://jovemnerd.com.br/nerdcast/?search=&theme=tecnologia&page=1"
    description  = "O Nerdcast completou 10 anos em 2016 com 1 milhão de downloads por episódio e como primeiro lugar de audiência em podcasts no Brasil."
    thumbnail = "/img/podcasts/jovemnerd.png"

[[params.links.podcast]]
    name = "Hipsters Tech"
    url = "http://hipsters.tech/"
    description  = "O Hipsters Ponto Tech é o podcast onde o pessoal da Caelum e da Alura entram em discussões sobre programação, design, UX, startups e as últimas modinhas em tecnologia. Ah! E sempre, com convidados especiais."
    thumbnail = "/img/podcasts/hipsters.png"

[[params.links.podcast]]
    name = "BlueSoft"
    url = "http://labs.bluesoft.com.br/category/podcast/"
    description  = "Podcast sobre desenvolvimento ágil, software e tecnologia, apresentado por André Faria, Luiz Farias Jr, e toda a equipe da Bluesoft"
    thumbnail = "/img/podcasts/bluesoft.png"

[[params.links.podcast]]
    name = "Área de Transferência"
    url = "http://areadetransferencia.com.br/episodes"
    description  = "Um podcast semanal sobre tecnologia, feito por 3 podcasters que já respiram o assunto diariamente."
    thumbnail = "/img/podcasts/areatransferencia.jpg"

[[params.links.podcast]]
    name = "PodProgramar"
    url = "https://mundopodcast.com.br/podprogramar/"
    description  = "Podcast apresentado por desenvolvedoras focado em programação, notícias e histórias, tudo com o toque feminino numa área dominada por homens."
    thumbnail = "/img/podcasts/podprogramar.png"

[[params.links.podcast]]
    name = "Lambda3"
    url = "https://www.lambda3.com.br/lambda3-podcast/"
    description  = "O Podcast da Lambda3 é um programa feito pelas pessoas que trabalham na Lambda3. Ele é feito 100% de acordo com os desejos das pessoas, sem viés tecnologico, sem viés de mercado, pensando em levar o melhor das discussões que ocorrem no dia-a-dia do desenvolvimento da Lambda3 para a comunidade técnica."
    thumbnail = "/img/podcasts/lambda3.png"

[[params.links.podcast]]
    name = "Área404"
    url = "http://agregarium.com.br/conteudos/area404/"
    description  = "Podcast de discussão sobre as principais notícias da semana no mundo da tecnologia."
    thumbnail = "/img/podcasts/area404.png"

[[params.links.podcast]]
    name = "Trico-Tech"
    url = "http://www.trico-tech.com/"
    description  = "Um podcast sobre tudo o que as mulheres curtem: vida digital, inteligência artificial, futurologia, robótica, genética e, é claro, games."
    thumbnail = "/img/podcasts/trico.png"

[[params.links.podcast]]
    name = "Castalio"
    url = "http://castalio.info/"
    description  = "O Castálio é um podcast semanal, publicado todas as segundas às 11 horas. Og, Elyézer e Bruno falam sobre tecnologia, desenvolvimento de software, linguagens de programação e o mundo do Open Source!"
    thumbnail = "/img/podcasts/castalio.png"

[[params.links.podcast]]
    name = "DEVNAESTRADA"
    url = "http://devnaestrada.com.br/"
    description  = "Podcast semanal sobre programação."
    thumbnail = "/img/podcasts/devnaestrada.png"
